services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_app
    ports:
      - "3001:3001"
    environment:
      NEXT_PUBLIC_GRAPHQL_ENDPOINT: http://localhost:3000/graphql
    volumes:
      - ./:/usr/src/app
      - frontend_node_modules:/usr/src/app/node_modules
    networks:
      - app-network

networks:
  app-network:
    external: true

volumes:
  frontend_node_modules: