services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_DATABASE: nestjs_db
    volumes:
      - ./:/usr/src/app # ソースコードをマウント
      - backend_node_modules:/usr/src/app/node_modules # node_modulesを名前付きボリュームに
    networks:
      - app-network

  # PostgreSQLデータベースサービス
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestjs_db
    volumes:
      - postgres_data:/var/lib/postgresql/data # DBデータを永続化
    networks:
      - app-network

# Dockerネットワークの定義
networks:
  app-network:
    driver: bridge

# Dockerボリュームの定義
volumes:
  postgres_data:
  backend_node_modules: